package ca.carleton.niklegault.justInvest;

public enum Actions {
    VIEW_ACCOUNT_BALANCE,
    VIEW_INVESTMENT_PORTFOLIO,
    VIEW_FINANCIAL_ADVISOR_INFO,
    VIEW_FINANCIAL_PLANNER_INFO,
    MODIFY_INVESTMENT_PORTFOLIO,
    VIEW_PRIVATE_CONSUMER_INSTRUMENTS,
    VIEW_MONEY_MARKET_INSTRUMENTS
}
